#!/usr/bin/env bash

escape_print_help() {
cat <<EOF
Escape whitespaces and specail characters in string.
Uses 'printf %q'. Read more in 'man printf'.

Usage:
    esc [OPTIONS]... [ARGS]...

Options:
    -o, --opts      add end of the options sign (double dash). See
                    SHELL BUILTIN COMMANDS in 'man bash' for more info.
    -h, --help      print this message and exit.
EOF
exit 0
}

escape_line() {
    while read -r UNESCAPED_LINE
    do
        # Double dash ("end of the options") EOF_OPTS to prevent
        #+interpretate filenames like this '-myfile' as shell options.
        echo "$EOF_OPTS$(printf '%q' "$UNESCAPED_LINE")"
    done < "${1:-/dev/stdin}"
}

if [[ ! "$@" ]] && [ -t 0 ]
then
    # Print help if no data sent to script
    escape_print_help
fi

while (( "$#" ))
do
    case "$1" in
        -o|--opts) EOF_OPTS='-- ';;
        -h|--help) escape_print_help;;
        -*|--*) echo "$0: Unknown option: $1" &>2; exit 1;;
        *) ARGS="$ARGS $1";;
    esac
    shift
done

if [ "$ARGS" ]
then
    escape_line <<< "$ARGS"
else
    escape_line
fi
