#!/usr/bin/env bash

set -o monitor   # for job control.
set -o errexit   # exit if error occurs.

R="\e[31m"       # red
Y="\e[33m"       # yellow
N="\e[0m"        # no color

# Defaults
HOST=0.0.0.0
PORT=8000
DIR=$PWD

# Check Python 3
if ! hash python3 2>/dev/null
then
    echo -e "${R}$0: Error: Python 3 executable not found.${N}" >&2
    exit 1
fi

http_print_help() {
cat <<EOF
Run Python 3 builtin HTTP Server.

Usage:
    http [OPTIONS]... [ARGS]...

Options:
    --cgi, cgi      run as CGI Server.
    -f, f           run Firefox.
    --help, help    print this message and exit.

Optional arguments:
    HOST            host to bind. Default: 0.0.0.0
    PORT            port to bind. Default: 8000
    DIR             directory to serve. Default: cwd.

Also HOST:PORT syntax is allowed.
EOF
exit 0
}

while (( "$#" ))
do
    case "$1" in
        -c|c|--cgi|cgi)
            CGI='--cgi';;
        -f|f|ff|--firefox|firefox)
            FOX=1;;
        -h|h|--help|help)
            http_print_help;;
        -*|--*)
            echo -e "${R}$0: Error: Bad option: $1${N}" >&2
            exit 1
            ;;
        *)
            if [ -d "$1" ]
            then
                # If direcory exists set it as root DIR.
                DIR="$1"
            elif [[ "$1" =~ ^[0-9]+$ ]]
            then
                # If value is integer set it as PORT.
                PORT="$1"
            elif [[ "$1" =~ \
                ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
            then
                # Value like IPv4 address. Not necessary.
                HOST="$1"
            elif [[ "$1" == 'localhost' ]]
            then
                # Nuff said.
                HOST="$1"
            elif [ "$(grep -o : <<<"$1")" ]
            then
                # If value like 'localhost:4000'
                HOST="$(echo "$1" | cut -d ":" -f 1)"
                PORT="$(echo "$1" | cut -d ":" -f 2)"
            else
                echo -e "${R}$0: Error: Bad option: $1${N}" >&2
                exit 1
            fi
            ;;
    esac
    shift
done

# Check available port and retry 3 times.
retries=1
while [ "$(ss -tanp | grep -o "$PORT")" ]
do
    if [[ "$retries" == 4 ]]
    then
        echo -e "${R}Max number of retries reached! Exiting.${N}" >&2
        exit 1
    else
        :
    fi

    # Increase port if is already in use.
    PORT_USED="$PORT"
    let PORT++
    echo -e "${R}Port $PORT_USED is already in use!${N}
        Switching to: $PORT" | sed 's/^ *//g' >&2

    let retries++
done

# Run Python http.server.
echo -e "Serve: $DIR\t${Y}Press ^C to stop serving.${N}"
python3 -m http.server $CGI --bind $HOST $PORT --directory $DIR &
[[ "$FOX" == 1 ]] && firefox http://$HOST:$PORT/
fg
