#!/usr/bin/env bash

prntl_version=0.4

LOG_FILE=prntl.log
TIME_FORMAT='%d %b %Y %T %z'
LOG_FORMAT='%time - %log'

prntl_print_help() {
cat << EOF
Print formatted log to STDOUT and log file.

Usage: prntl [-v| --version] [-h | --help] [-o | --output=<file>]
             [-f | --log-format=<string>] [-t | --time-format=<string>]
             [-p | --no-print] [-c | --no-color] [<string>]

Options:
    -o, --output=<file>         set log file name. Default: $LOG_FILE.
    -f, --log-format=<string>   set log format. Formatting options:
        %time   time; see '--time-format'. Default: $TIME_FORMAT
        %log    log string. Default: $LOG_FORMAT
    -t, --time-format=<string>  set time format; see 'date --help'
                                or 'man date' for details.
                                Example: prntl -t '%D %T'
    -c, --no-color              remove ANSI color codes from log string.
    -p, --no-print              don't print log to STDOUT.
    -h, --help                  print this help message and exit.
    -v, --version               print version and exit.
EOF
exit 0
}

prntl_get_optarg() {
    if [[ "$1" =~ .+=.+ ]]; then
        opt="${1%%=*}"; arg="${1#*=}"; sft=1
    elif [[ ! "$1" =~ .+=$ ]] && \
         [ "$2" ] && [ "${2:0:1}" != '-' ]
    then
        opt="$1"; arg="$2"; sft=2
    else
        opt="$1"
        if [[ "$1" =~ .+=$ ]]; then opt="${1:0: -1}"; fi
        echo "$0: Missing argument for: $opt" >&2
        exit 1
    fi
}

prntl_log_formatter() {
    echo "$1" | sed -e "s/%time/$(date +"$TIME_FORMAT")/g; s/%log/$2/g"
}

prntl_print_log() {
    if [ "$LOG" ]
    then
         LOG_MESSAGE="$LOG"
    else
        LOG_MESSAGE="$(cat <&0)"
    fi

    ESCAPED_LOG_MESSAGE="$(printf '%s\n' "$LOG_MESSAGE" | sed -e 's/[\/&]/\\&/g')"

    [ "$REMOVE_COLORS" ] && \
    ESCAPED_LOG_MESSAGE="$(echo "$ESCAPED_LOG_MESSAGE" | sed 's/\x1b\[[^\x1b]*m//g')"

    while IFS= read -r LOG_LINE
    do
        if [ "$NO_PRINT" ]
        then
            prntl_log_formatter "$LOG_FORMAT" "$LOG_LINE" >> "$LOG_FILE"
        else
            prntl_log_formatter "$LOG_FORMAT" "$LOG_LINE" | tee -a "$LOG_FILE"
        fi
    done <<< "$ESCAPED_LOG_MESSAGE"
}

if [[ ! "$@" ]] && [ -t 0 ]
then
    # Print help if no data sent to script.
    prntl_print_help
fi

while (( "$#" ))
do
    case "$1" in
        -o|--output|--output=*)
            prntl_get_optarg "$1" "$2"
            LOG_FILE="$arg"
            shift "$sft";;
        -f|--log-format|--log-format=*)
            prntl_get_optarg "$1" "$2"
            LOG_FORMAT="$arg"
            shift "$sft";;
        -t|--time-format|--time-format=*)
            prntl_get_optarg "$1" "$2"
            TIME_FORMAT="$arg"
            shift "$sft";;
        -c|--no-color)
            REMOVE_COLORS=1
            shift;;
        -p|--no-print)
            NO_PRINT=1
            shift;;
        -h|--help)
            prntl_print_help;;
        -v|--version)
            echo "prntl v$prntl_version"; exit 0;;
        -*)
            echo -e "$0: Unknown option: $1\nSee 'prntl --help'." >&2
            exit 1;;
        *)
            LOG+="$1 "
            shift;;
    esac
done

prntl_print_log $LOG
