#!/usr/bin/env bash

LOG_FILE=prntl.log
TIME_FORMAT='%d %b %Y %T %z'
LOG_FORMAT='%time - %log'

prntl_print_help() {
cat << EOF
Print formatted log to STDOUT and log file.

Usage:
    prntl [OPTIONS]... [ARGUMENTS]...

Options:
    -o, --output        set log file name. Default: printl.log.
    -f, --log-format    set log format. Formatting options:
                            %time   time; see '--time-format'.
                            %log    log string.
                        Example: prntl -f 'mylog %time : %log'
    -t, --time-format   set time format; see 'date --help'
                        or 'man date' for details.
                        Example: prntl -t '%D %T'
    -c, --no-color      remove ANSI color codes from log string.
    -p, --no-print      don't print log to STDOUT.
    -h, --help          show this help message and exit.
EOF
exit 0
}

prntl_log_formatter() {
    echo "$1" | sed -e "s/%time/$(date +"$TIME_FORMAT")/g; s/%log/$2/g"
}

prntl_print_log() {
    if [ "$LOG" ]
    then
         LOG_MESSAGE="$LOG"
    else
        LOG_MESSAGE="$(cat <&0)"
    fi

    ESCAPED_LOG_MESSAGE="$(printf '%s\n' "$LOG_MESSAGE" | sed -e 's/[\/&]/\\&/g')"

    [ "$REMOVE_COLORS" ] && \
    ESCAPED_LOG_MESSAGE="$(echo "$ESCAPED_LOG_MESSAGE" | sed 's/\x1b\[[^\x1b]*m//g')"

    while IFS= read -r LOG_LINE
    do
        if [ "$NO_PRINT" ]
        then
            prntl_log_formatter "$LOG_FORMAT" "$LOG_LINE" >> "$LOG_FILE"
        else
            prntl_log_formatter "$LOG_FORMAT" "$LOG_LINE" | tee -a "$LOG_FILE"
        fi
    done <<< "$ESCAPED_LOG_MESSAGE"
}

if [[ ! "$@" ]] && [ -t 0 ]
then
    # Print help if no data sent to script.
    prntl_print_help
fi

while (( "$#" ))
do
    case "$1" in
        -o|--output)
            if [ "$2" ] && [ ${2:0:1} != '-' ]
            then
                LOG_FILE="$2"
                shift
            else
                echo "$0: Missing argument for $1" >&2
                exit 1
            fi
            shift
            ;;
        -f|--log-format)
            if [ "$2" ] && [ ${2:0:1} != '-' ]
            then
                LOG_FORMAT="$2"
                shift
            else
                echo "$0: Missing argument for $1" >&2
                exit 1
            fi
            shift
            ;;
        -t|--time-format)
            if [ "$2" ] && [ ${2:0:1} != '-' ]
            then
                TIME_FORMAT="$2"
                shift
            else
                echo "$0: Missing argument for $1" >&2
                exit 1
            fi
            shift
            ;;
        -c|--no-color)
            REMOVE_COLORS=1
            shift
            ;;
        -p|--no-print)
            NO_PRINT=1
            shift
            ;;
        -h|--help)
            prntl_print_help
            ;;
        -*)
            echo -e "$0: Unknown option: $1\nSee 'prntl --help'." >&2
            exit 1
            ;;
        *)
            LOG+="$1 "
            shift
            ;;
    esac
done

prntl_print_log $LOG
