#!/usr/bin/env bash

if ! hash highlight 2>/dev/null
then echo "$0: highlight executable not found." >&2 && exit 1
fi

view_print_help() {
cat << EOF
Print highlighted text to STDOUT.

Usage:
    view [OPTIONS..] [ARGUMENTS]...

Options:
    -l --less   send output to 'less -R'
    -n --lines  less, but shows line nums (less -RN).
    -h --help   show this help message and exit.
EOF
exit 0
}

view_print() {
    cat "${1:-/dev/stdin}" | highlight -O ansi
}

# Do nothing if no arguments passed and no STDIN.
[[ -t 0 && -z "$1" ]] && view_print_help

while (( "$#" )); do
    case $1 in
        -l|--less)
            LESS_R=1;;
        -n|-ln|-nl|--lines)
            LESS_R=1
            LESS_RN=1;;
        -h|--help)
            view_print_help;;
        *)
            if [ -f "$1" ]
            then
                INPUT_FILE="$1"
            else
                echo "$0: No such file: $1" >&2
                exit 1
            fi
            ;;
    esac
    shift
done

if [ "$LESS_R" ] && [ ! "$LESS_RN" ]
then
    view_print "$INPUT_FILE" | less -R
elif [ "$LESS_R" ] && [ "$LESS_RN" ]
then
    view_print "$INPUT_FILE" | less -RN
else
    view_print "$INPUT_FILE"
fi
